[package]
name = "action-validator"
version = "0.0.0-git"
authors = ["Matt Palmer <matt@hezmatt.org>"]
edition = "2018"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
glob = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
valico = "3.6"
