[package]
name = "action-validator"
description = "Validator for GitHub action and workflow YAML files"
license = "GPL-3.0-only"
homepage = "https://github.com/mpalmer/action-validator"
repository = "https://github.com/mpalmer/action-validator"
include = [
	"/LICENCE",
	"/src/*.rs",
	"/src/schemastore/src/schemas/json/github-workflow.json",
	"/src/schemastore/src/schemas/json/github-action.json"
]
version = "0.0.0-git"
authors = ["Matt Palmer <matt@hezmatt.org>"]
edition = "2018"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
glob = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
valico = "3.6"
