name: Build binaries

on: [push]

jobs:
  build:
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          override: true
          default: true

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
