name: Upload binaries to release

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: action-validator_linux_amd64
          - os: macos-latest
            asset_name: action-validator_darwin_amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/release/action-validator
          asset_name: ${{ matrix.asset_name }}
